### ISSUE TITLE
[mesheryctl] `mesheryctl system config aks` does not support Windows

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1957] opened 2020-11-20 13:13 UTC
**Description**
`mesheryctl system config aks` assumes that *nix is the OS that the user is running this command on.

**Expected Behavior**
This command needs made to be Windows-friendly. Windows doesn't have a $HOME environment variable.

**Logs**
```
Error getting contexts : open $HOME/.meshery/aks-kubeconfig.yaml: The system cannot find the path specified.
```

**Reported by**
- @hippoz, @nikita15p

**Comment by kushthedude** [comment] 2020-11-20 13:16
Duplicate of #1894

**Closed by kushthedude** 2020-11-20 13:16 UTC
Labels: component/mesheryctl, kind/bug

**Comment by leecalcote** [comment] 2020-11-20 13:18
@kushthedude will you either reopen this issue and convert one of the two of the issues to cover `gcp` and `minikube` or will you update #1894 to cover all three of them?

**Comment by leecalcote** [comment] 2020-11-20 13:19
Also, include @hippoz and @nikita15p handles one whichever remains open, so that they may be informed of progress and test when the issue has been fixed.

**Comment by kushthedude** [comment] 2020-11-20 13:21
Sure updating #1894
