### ISSUE TITLE
Namespace creation for custom app on linkerd

### ISSUE THREAD

**Issue by prateeksahu** [layer5io/meshery#101] opened 2019-04-28 21:35 UTC
When we try to deploy a custom app using yaml on a new namespace, the app deployment fails because the new namespace is not created.

1. Configure Linkerd
2. Go to Playground -> Linkerd
3. Give a new namespace and click on custom Yaml
4. Provide a custom yaml file and click Submit

**Expected behavior**
The provided app should be deployed.
We see error message: meshery-linkerd_1  | time="2019-04-28T21:24:02Z" level=warning msg="unable to create the requested resource, attempting operation without namespace: namespaces \"linkerdapp\" not found"

**Comment by leecalcote** [comment] 2019-04-28 22:50
@girishranganathan is this an issue in Meshery or the Linkerd adapter?

**Comment by girishranganathan** [comment] 2019-04-28 22:56
It is not a bug. I was just explaining to @prateeksahu. 
When using custom yaml, if a namespace needs to be created, it should be included in the yaml. 
Reason: a custom yaml could contain any valid k8s yaml which Meshery and its adapters today don't try to interpret today. Their goal, atm, is just to apply the given yaml as it is.
When @prateeksahu updated his yaml to include the namespace block in it, it worked as expected.

**Comment by leecalcote** [comment] 2019-04-28 22:58
Updated issue with "docs" label.

**Comment by girishranganathan** [comment] 2019-08-07 14:22
The reported message is just a warning. I will close this issue for now. We can reopen if it is really an issue.

**Closed by girishranganathan** 2019-08-07 14:22 UTC
Labels: docs, linkerd
