### ISSUE TITLE
[mesheryctl] Context: Allow deployment of specified version of meshery using mesheryctlcontext

### ISSUE THREAD

**Issue by anirudhjain75** [layer5io/meshery#2208] opened 2021-01-05 18:40 UTC

**Comment by leecalcote** [comment] 2021-01-05 20:03
This issue depends on https://github.com/meshery/meshery/issues/2164

**Comment by leecalcote** [comment] 2021-01-13 18:20
This is a duplicate of #2208

**Closed** 2021-01-13 18:20 UTC
Labels: area/lifecycle, component/mesheryctl, issue/duplicate, kind/enhancement

**Comment by anirudhjain75** [comment] 2021-01-13 18:27
> This is a duplicate of #2208

Its #2246
