### ISSUE TITLE
[mesheryctl]

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#3255] opened 2021-06-22 17:50 UTC
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
A grammatical error exists in the output from the `mesheryctl system stop` command when Meshery is deployed in K8s cluster.

#### Desired Behavior
This output should read:

```
➜  ~ mesheryctl system stop
Meshery deployments will be deleted from your cluster. Are you sure you want to continue [y/n]? y
Stopping Meshery...
Pods terminated.
Meshery is stopped.
```

#### Screenshots/Logs
```
➜  ~ mesheryctl system stop
Meshery deployments will be deleted from your cluster. Are you sure you want to continue [y/n]? y
Stopping Meshery...
Pods terminatedeshery pods
Meshery is stopped.
```

#### Environment

- Host OS: Mac
- Meshery Client Version: stable-v0.5.25
- Platform: Kubernetes

---

#### Contributor Resources

- [mesheryctl Contributing Guide](https://github.com/layer5io/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sayantan1413** [comment] 2021-06-23 07:53
Hey @leecalcote I would like to work on this issue.

**Comment by sayantan1413** [comment] 2021-06-23 08:59
Hey @hexxdump I was trying to reproduce this error in ubuntu18.04 deployed in k8s but I cannot reproduce the error. Is this error particular to MacOS?

**Comment by sayantan1413** [comment] 2021-06-23 12:07
Hello @hexxdump and @leecalcote I found that in [stop.go](https://github.com/sayantan1413/meshery/blob/master/mesheryctl/internal/cli/root/system/stop.go) in line 177 it written 
`s := utils.CreateDefaultSpinner("Terminating Meshery pods", "Pods terminated")`
so it should show "poda terminated" but it is showing "Pods terminatedeshery pods" And while solving this I found that if I modify the **final message paramete**r i.e is "Pods terminated" to "Pods terminated from meshery" the error vanishes.
![Screenshot from 2021-06-23 17-31-25](https://user-images.githubusercontent.com/64970095/123093567-796fc000-d449-11eb-9a7c-ae6beb406443.png)
Should I move ahead with this approach or should I do it in another way?

**Comment by DantrazTrev** [comment] 2021-06-23 12:45
Hei @sayantan1413 , I had a different approach for the issue that I hope might help in this case and I did some digging that

 From the spinner, we are using [here](https://github.com/briandowns/spinner), The `FinalMSG` is appended over the `suffix`

 We might prefer adding a new line for the `FinalMSG` or better yet changing the `suffix` text to blank after the exexcution Although this might hinder some of the other use cases?(And I'm not sure if it works)

**Comment by hexxdump** [comment] 2021-06-23 12:57
> Hello @hexxdump and @leecalcote I found that in [stop.go](https://github.com/sayantan1413/meshery/blob/master/mesheryctl/internal/cli/root/system/stop.go) in line 177 it written
> `s := utils.CreateDefaultSpinner("Terminating Meshery pods", "Pods terminated")`
> so it should show "poda terminated" but it is showing "Pods terminatedeshery pods" And while solving this I found that if I modify the **final message paramete**r i.e is "Pods terminated" to "Pods terminated from meshery" the error vanishes.
> 
> ![Screenshot from 2021-06-23 17-31-25](https://user-images.githubusercontent.com/64970095/123093567-796fc000-d449-11eb-9a7c-ae6beb406443.png)
> 
> Should I move ahead with this approach or should I do it in another way?
> 
> Note: I have modified `Meshery deployments will be deleted from sayantan cluster. Are you sure you want to continue [y/n]? y` for testing purpose I will change it to the previous state when making the pr.

FinalMSG (Pods terminated) is overwritten over the (stale) Suffix (Terminating Meshery pods).
Would it help if we reset the s.Suffix at line: 195 before calling s.Stop()?

// @navendu-pottekkat

**Comment by hexxdump** [comment] 2021-06-23 12:59
> Hei @sayantan1413 , I had a different approach for the issue that I hope might help in this case and I did some digging that
> 
> From the spinner, we are using [here](https://github.com/briandowns/spinner), The `FinalMSG` is appended over the `suffix`
> 
> We might prefer adding a new line for the `FinalMSG` or better yet changing the `suffix` text to blank after the exexcution Although this might hinder some of the other use cases?(And I'm not sure if it works)

+1

**Comment by sayantan1413** [comment] 2021-06-23 16:19
Hey @DantrazTrev and @hexxdump I tried your approaches but this problem still persists.

**Comment by DantrazTrev** [comment] 2021-06-23 16:24
> Hey @DantrazTrev and @hexxdump I tried your approaches but this problem still persists.

Hei @sayantan1413 would you mind me giving it a try ? It worked when I played with spinner library in the sandbox.

**Comment by sayantan1413** [comment] 2021-06-23 16:30
Yeah sure I am assigning this to you.

**Closed** 2021-06-25 05:30 UTC
Labels: component/mesheryctl, good first issue, help wanted, kind/bug, language/go
