### ISSUE TITLE
[UI] Icons not scaling with browser zoom in/out

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1146] opened 2020-06-17 20:24 UTC
**Description**
When a user zooms in or out in their web browser, Meshery UI's icons remain a constant size.

**Expected Behavior**
Icons should scale large and small proportional to the user agent's (web browser's) zoom level.

**Screenshots**
This screenshot shows a web browser session zoomed in. The icons in this screenshot should be much larger.

**Browser**
This issue only affects the Safari browser. 

<img width="1969" alt="Screen Shot 2020-06-17 at 3 07 20 PM" src="https://user-images.githubusercontent.com/7570704/84946468-65fb7d80-b0ae-11ea-8444-7dad4d906e75.png">

**Comment by ishita-kumar** [comment] 2020-06-19 22:43
Is this issue still open? I'd like to work on it! From what I notice, the icons on top are scaling while zooming in and out however the tabs in Grafana and prometheus as well as the Settings icon in Configure Prometheus are dis-functioning.
Screenshot Of the Issue:
https://imgur.com/1F2zfwv

**Comment by leecalcote** [comment] 2020-06-20 00:49
@ishita-kumar Yes, please do grab this one. 👍

**Comment by leecalcote** [comment] 2020-06-20 01:25
Related to #567

**Comment by morelmiles** [comment] 2020-08-27 19:38
Any progress on this?

**Comment by leecalcote** [comment] 2020-08-27 21:51
@morelmiles, no, we're still in the same place here. You're help would be much appreciated. Here's a recent screenshot:

<img width="1076" alt="Screen Shot 2020-08-27 at 4 50 18 PM" src="https://user-images.githubusercontent.com/7570704/91498498-7afe4500-e885-11ea-8bbd-4d384dc5c071.png">


Notice the hamburger icon (menu) also not being responsive.

**Comment by leecalcote** [comment] 2020-08-27 21:52
@morelmiles jump into the community Slack at http://slack.meshery.io, if any questions arise or just to better connect with the community and familiarize with the projects. 👍

**Comment by luigimorel** [comment] 2020-08-28 08:04
Thanks. Will get onto it.


---
Luigi Morel.

Front-end developer and UI/UX designer.

Tel: +256 704 916 696 (WhatsApp)

**Comment by PluckyPrecious** [comment] 2020-09-20 18:32
> Thanks. Will get onto it.
> […](#)

Hello @moreImiles how is this coming up?😊

**Comment by leecalcote** [comment] 2020-10-21 02:07
@morelmiles, we'll go ahead and unassign so another contributor can pick this up. Feel free to grab any other open issue.

**Comment by luigimorel** [comment] 2020-10-21 09:33
Hey,
I couldn't set up on my computer. Feel free to assign to another
contributor. My regrets.


---
Luigi Morel.

Front-end developer and UI/UX designer.

Tel: +256 704 916 696 (WhatsApp)

**Comment by sharmaaditya570191** [comment] 2020-11-22 15:49
Hi @leecalcote . I have built meshery on my system. Is this still an issue?
Here is a screenshot when zoomed to 150%. It is working fine on my system.
![image](https://user-images.githubusercontent.com/42587159/99908349-30675a00-2d08-11eb-9f42-92012e983ced.png)

**Comment by leecalcote** [comment] 2020-11-22 15:59
@sharmaaditya570191 thank you. This issue seems to only be affecting Safari.

**Comment by yolossn** [comment] 2020-12-29 22:36
I am able to reproduce this using Safari. The same issue is affecting the icons in the navigation bar also (Refer screenshot). 
The icons in the Navigation bar use font-awesome and I found a similar [issue](https://github.com/FortAwesome/Font-Awesome/issues/13032). Looks like Safari doesn't scale SVG based on zoom



![image](https://user-images.githubusercontent.com/22731013/103317848-7d022b80-4a52-11eb-8de7-7a8b5bd5c7fe.png)

**Comment by leecalcote** [comment] 2020-12-30 04:23
Thank you for having a look into this @yolossn. 👍 FYI - an attempt to work-around - https://github.com/meshery/meshery/pull/1914

@pranshukharkwal FYI (see linked issue).

**Comment by Naimaoye** [comment] 2021-04-08 12:02
Hi @leecalcote, is this issue still open? If yes, I would like to work on it

**Comment by leecalcote** [comment] 2021-04-08 21:26
Hi @Naimaoye, yes, please.

**Comment by Naimaoye** [comment] 2021-04-10 13:54
Hi @leecalcote could you please unassign this to me. I realized that I am only supposed to contribute to mesheryctl

**Comment by leecalcote** [comment] 2021-04-10 15:06
Hi @Naimaoye, you bet. 

Please know that you’re most welcome to contribute anywhere you have an interest. 👍

**Comment by Ayush-Khandelwal-007** [comment] 2021-05-14 20:47
Hi @leecalcote ,I would like to work on it.

**Closed** 2021-05-16 23:05 UTC
Labels: component/ui, good first issue, help wanted, issue/willfix, kind/bug, language/javascript, priority/low
