### ISSUE TITLE
Installation: Request for sudo password is lost among other script output

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#643] opened 2020-01-31 18:09 UTC
**Current Behavior**
While running the latest `meshery` installation script on macOS in zsh, users don't necessary see the prompt for sudo permissions. See screenshot.

**Screenshot**
<img width="1068" alt="Screen Shot 2020-01-31 at 12 06 41 PM" src="https://user-images.githubusercontent.com/7570704/73563240-7aeab380-4422-11ea-9c93-a4571773376d.png">

Related to #642

**Comment by leecalcote** [comment] 2020-01-31 18:11
@anandrkskd @nupur-thakur fyi

**Comment by nupur-thakur** [comment] 2020-01-31 18:17
@leecalcote  Sir I not sure if I am right or not but have you ran any sudo command before this if so then this can be one of the reason of not asking the password.

**Comment by leecalcote** [comment] 2020-01-31 18:18
@nupur-thakur good thinking. No, this was run in a fresh terminal session. The user is actually prompted for the password, but its lost and hidden among other script output - 

<img width="1068" alt="Screen Shot 2020-01-31 at 12 06 41 PM" src="https://user-images.githubusercontent.com/7570704/73563786-cce00900-4423-11ea-8990-86b6d33b6e0b.png">

**Comment by nupur-thakur** [comment] 2020-01-31 18:41
I tried the same cmd in Ubuntu 18.04 and it is ignoring the request for password in Ubuntu as well.
![Screenshot from 2020-02-01 00-06-14](https://user-images.githubusercontent.com/39610703/73565303-465d1300-4487-11ea-8bbb-40b3da4a92e5.png)

**Comment by anandrkskd** [comment] 2020-02-01 04:14
Understood! @nupur-thakur would you like to work on this issue? I will help you on this issue if you would.

**Comment by nupur-thakur** [comment] 2020-02-01 05:58
Yes. Definitely. Thanks @anandrkskd

**Comment by nupur-thakur** [comment] 2020-02-11 15:10
This issue should be reopened as the problem is still not resolved with the curl command.
The possible solution could be using just `bash` instead of `sudo bash` and using sudo with only `mv` command in the bash.

**Closed** 2020-02-14 07:17 UTC
Labels: bug
